In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import sklearn

In [2]:
df = pd.read_csv(r"D:\Data Science\science\Dataset\heart_failure_clinical_records_dataset.csv")
df

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                       582         0                 20   
1    55.0        0                      7861         0                 38   
2    65.0        0                       146         0                 20   
3    50.0        1                       111         0                 20   
4    65.0        1                       160         1                 20   
..    ...      ...                       ...       ...                ...   
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                      1  265000.00               1.9           130    1   
1                      0  263358.03               1.1           136    1   
2                      0  162000.00               1.3           129    1   
3                      0  210000.00               1.9           137    1   
4                      0  327000.00               2.7           116    0   
..                   ...        ...               ...           ...  ...   
294                    1  155000.00               1.1           143    1   
295                    0  270000.00               1.2           139    0   
296                    0  742000.00               0.8           138    0   
297                    0  140000.00               1.4           140    1   
298                    0  395000.00               1.6           136    1   

     smoking  time  DEATH_EVENT  
0          0     4            1  
1          0     6            1  
2          1     7            1  
3          0     7            1  
4          0     8            1  
..       ...   ...          ...  
294        1   270            0  
295        0   271            0  
296        0   278            0  
297        1   280            0  
298        1   285            0  

[299 rows x 13 columns]

In [3]:
x = df.drop(columns = ['DEATH_EVENT'])
y = df['DEATH_EVENT']

In [4]:
x

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                       582         0                 20   
1    55.0        0                      7861         0                 38   
2    65.0        0                       146         0                 20   
3    50.0        1                       111         0                 20   
4    65.0        1                       160         1                 20   
..    ...      ...                       ...       ...                ...   
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                      1  265000.00               1.9           130    1   
1                      0  263358.03               1.1           136    1   
2                      0  162000.00               1.3           129    1   
3                      0  210000.00               1.9           137    1   
4                      0  327000.00               2.7           116    0   
..                   ...        ...               ...           ...  ...   
294                    1  155000.00               1.1           143    1   
295                    0  270000.00               1.2           139    0   
296                    0  742000.00               0.8           138    0   
297                    0  140000.00               1.4           140    1   
298                    0  395000.00               1.6           136    1   

     smoking  time  
0          0     4  
1          0     6  
2          1     7  
3          0     7  
4          0     8  
..       ...   ...  
294        1   270  
295        0   271  
296        0   278  
297        1   280  
298        1   285  

[299 rows x 12 columns]

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [9]:
x_train

array([[ 1.69821258e+00, -8.71104775e-01,  4.08620602e+00, ...,
         7.35688190e-01,  1.45416070e+00, -3.00201030e-01],
       [-9.12335403e-01, -8.71104775e-01, -4.09677121e-01, ...,
         7.35688190e-01,  1.45416070e+00, -2.35671837e-01],
       [-1.33339153e+00, -8.71104775e-01,  1.65728387e-04, ...,
         7.35688190e-01, -6.87681906e-01, -8.93869609e-01],
       ...,
       [ 2.03505748e+00,  1.14796753e+00, -4.95362150e-01, ...,
        -1.35927151e+00, -6.87681906e-01, -4.67976933e-01],
       [-7.02231493e-02, -8.71104775e-01,  1.65728387e-04, ...,
         7.35688190e-01,  1.45416070e+00, -1.16489222e+00],
       [ 7.71889104e-01,  1.14796753e+00, -4.24130017e-01, ...,
         7.35688190e-01,  1.45416070e+00,  2.03126678e-01]])

In [10]:
from sklearn.neighbors import KNeighborsClassifier
nc = KNeighborsClassifier(n_neighbors=3)
nc.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [11]:
y_pred = nc.predict(x_test)
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

In [12]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
confusion_matrix(y_test, y_pred)

array([[35,  2],
       [18,  5]], dtype=int64)

In [13]:
accuracy_score(y_test, y_pred)

0.6666666666666666

In [14]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.66      0.95      0.78        37
           1       0.71      0.22      0.33        23

    accuracy                           0.67        60
   macro avg       0.69      0.58      0.56        60
weighted avg       0.68      0.67      0.61        60

