In [ ]:
import sklearn
import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [6]:
df = pd.read_csv(r"C:\Users\Shashank\Downloads/50_Startups.csv")
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [7]:
x = df.drop(columns='Profit')
y = df['Profit']

In [8]:
x.head()

R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida

In [9]:
df['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [10]:
x = pd.get_dummies(data=x,columns=['State'],drop_first=True)
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [11]:
from sklearn.preprocessing import RobustScaler
sc = RobustScaler()
x[['R&D Spend','Administration','Marketing Spend']] = sc.fit_transform(x[['R&D Spend','Administration','Marketing Spend']])
x.head()

R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   1.496732        0.345355         1.522416          False            True
1   1.452113        0.697565         1.358546          False           False
2   1.303634       -0.524290         1.147203           True           False
3   1.156567       -0.097977         1.001848          False            True
4   1.119836       -0.761543         0.901764           True           False

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=102)

In [13]:
x_train

R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
31  -0.193212        0.729778        -0.731614          False            True
33  -0.284711       -0.477784         0.011275           True           False
19   0.216789        0.749534        -1.250030          False            True
24   0.064750       -0.569635        -0.423940          False            True
10   0.468034       -0.294461         0.096638           True           False
12   0.337504        0.112392         0.218155           True           False
17   0.350370        0.544322         0.410522          False            True
30  -0.179297       -0.171693        -0.714496           True           False
42  -0.801249       -0.644839        -0.380299          False           False
5    0.953936       -0.556662         0.882330          False            True
22   0.015300        0.002018         0.532430           True           False
6    0.998345        0.595921        -0.499500          False           False
11   0.447908       -0.751841         0.217597          False           False
46  -1.163285       -0.167438         0.495967           True           False
36  -0.719797        0.105966        -0.068105           True           False
40  -0.718328       -0.101037        -0.234594          False           False
38  -0.856568       -1.380444        -0.161317          False            True
48  -1.175827       -1.725964        -1.250030          False            True
35  -0.438440       -0.915864        -0.042303          False            True
27  -0.015300        0.125629         0.825459          False            True
28  -0.113507        1.458133        -0.555730           True           False
25  -0.135996        0.409945        -0.439291          False           False
39  -0.559341       -0.966102        -0.221644          False           False
16   0.080466       -0.026811         0.303403          False           False
49  -1.184617       -0.139037        -0.984570          False           False
32  -0.156361        0.158589        -0.979209          False           False
3    1.156567       -0.097977         1.001848          False            True
18   0.303213       -0.207340         0.483069           True           False
4    1.119836       -0.761543         0.901764           True           False
7    0.928334        0.555328         0.653236           True           False
15   0.672530       -0.002018         0.288302          False            True
44  -0.824976        0.780961        -1.083520          False           False
45  -1.168397        0.035349        -1.238841          False            True
8    0.770134        0.632895         0.581170          False            True
9    0.815416       -0.341041         0.542199          False           False
43  -0.933171        0.113898        -1.041213          False            True
2    1.303634       -0.524290         1.147203           True           False
47  -1.184617        0.309577        -1.250030          False           False
14   0.760416        0.823317         0.257372           True           False
0    1.496732        0.345355         1.522416          False            True

In [14]:
y_train

31     97483.56
33     96778.92
19    122776.86
24    108552.04
10    146121.95
12    141585.52
17    125370.37
30     99937.59
42     71498.49
5     156991.12
22    110352.25
6     156122.51
11    144259.40
46     49490.75
36     90708.19
40     78239.91
38     81229.06
48     35673.41
35     96479.51
27    105008.31
28    103282.38
25    107404.34
39     81005.76
16    126992.93
49     14681.40
32     97427.84
3     182901.99
18    124266.90
4     166187.94
7     155752.60
15    129917.04
44     65200.33
45     64926.08
8     152211.77
9     149759.96
43     69758.98
2     191050.39
47     42559.73
14    132602.65
0     192261.83
Name: Profit, dtype: float64

In [15]:
x_test

R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
37  -0.469966       -1.737154        -0.092184          False           False
23  -0.089490       -0.412265         0.540948           True           False
26   0.036937        0.521418        -0.462283           True           False
20   0.051937       -0.214843         0.505076          False           False
29  -0.120740        0.737808        -0.620430          False            True
1    1.452113        0.697565         1.358546          False           False
21   0.086569        0.755842         0.511380          False            True
13   0.307158        0.311235         0.234759          False           False
34  -0.431759        0.851204        -0.011275          False           False
41  -0.732297       -0.924053        -0.283515           True           False

In [16]:
y_test

37     89949.14
23    108733.99
26    105733.54
20    118474.03
29    101004.64
1     191792.06
21    111313.02
13    134307.35
34     96712.80
41     77798.83
Name: Profit, dtype: float64

In [17]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model = lr.fit(x_train,y_train)
model

LinearRegression()

In [18]:
y_pred = lr.predict(x_test)
y_pred

array([ 87945.70380182, 110085.98872324, 111615.52071114, 114130.41030041,
       102472.90309253, 186101.26707243, 116826.18732432, 125256.95283048,
        86591.67464092,  75650.68475618])

In [20]:
train_acc = lr.predict(x_train)
train_acc

array([ 98458.20825457,  98522.11944396, 117170.06832788, 114262.41990486,
       136322.46865323, 129644.75198575, 129992.14983512, 100835.66348889,
        68817.54705264, 163433.93383857, 114742.51313791, 156947.86279476,
       133715.54325794,  55738.35077629,  75620.6709182 ,  72741.84385083,
        70093.55946484,  50727.09601172,  90844.15953216, 113687.52773904,
       102455.24960438, 100525.34531715,  81949.0284317 , 114593.56868855,
        46770.65780888,  97950.06960266, 173386.7572169 , 129295.92281355,
       172485.20815396, 160198.23549838, 146469.61934938,  63195.86029978,
        48720.11881081, 151522.85436393, 152724.4710912 ,  61104.45241683,
       182240.56352741,  45220.80180389, 150016.3119981 , 191669.00493338])

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9649748132881202

In [22]:
r2_score(y_train,train_acc)

0.9478393895388706

In [23]:
print(sc.transform([[165349.2,136897.80,471784.10]]))

[[1.49673201 0.34535525 1.52241555]]


c:\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RobustScaler was fitted with feature names
  warnings.warn(


In [25]:
lr.predict([[165349.2,136897.80,471784.10,0,1]])

c:\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([9.7641936e+09])

In [26]:
pickle.dump(lr,open('ML model.pkl','wb'))