In [2]:
# 1. Import NumPy and check its version.

import numpy

numpy.__version__

'1.26.4'

In [2]:
# 2. Create a 1D NumPy array of numbers from 1 to 10.

print(numpy.arange(1, 11))

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# 3. Create a 2D NumPy array of shape (3,3) filled with zeros.

print(numpy.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# 4. Create a 3x3 identity matrix.

print(numpy.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# 5. Generate a NumPy array of 10 random numbers between 0 and 1.

import numpy as np

np.random.rand(10)

array([0.63577798, 0.36023082, 0.43114718, 0.47423763, 0.77212997,
       0.60006897, 0.19487162, 0.93788085, 0.30066132, 0.89218943])

In [30]:
# 6. Create an array of even numbers from 2 to 20.

np.arange(2, 21, 2)


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [31]:
# 7. Reverse a NumPy array.

arr = np.array([1,2,3,4,5])
arr[::-1]

array([5, 4, 3, 2, 1])

In [33]:
# 8. Find the maximum and minimum values in an array.

arr = np.array([1,2,3,4,5])

print(arr.max())
print(arr.min())

5
1


In [10]:
# 9. Find the mean, median, and standard deviation of an array.
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,0])

print(np.std(arr))
print(np.median(arr))
print(np.mean(arr))

2.8722813232690143
4.5
4.5


In [27]:
# 10. Reshape a 1D array into a 2D array.

import numpy as np

arr = np.array([1,2,3,4,5])
# np.reshape(arr, (1, 5))
print(arr)



[1 2 3 4 5]


In [34]:
# 11. Create a 4x4 matrix with values ranging from 0 to 15.

import numpy as np

arr = np.arange(0, 16).reshape(4, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [45]:
# 12. Extract the diagonal elements of a matrix.

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,0,11,12,13,14,15,16]).reshape(4, 4)
print(np.diag(arr))


[ 1  6 11 16]


In [47]:
# 13. Find the sum of all elements in an array.
import numpy as np 
 
arr = np.array([1,2,3,4,5,6,7,8])

arr = arr.sum()
print(arr)

36


In [2]:
# 14. Find the cumulative sum of elements in an array.

import numpy as np
arr = np.array([1, 2, 3, 4, 5])

cumulative_sum = np.cumsum(arr)
print(cumulative_sum)


[ 1  3  6 10 15]


In [5]:
# 15. Create a NumPy array with linearly spaced values between 0 and 1.

import numpy as np
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [14]:
# 16. Create an array of 20 random integers between 50 and 100.
import numpy as np

arr = np.random.randint(50, 100, 20)
print(arr)

[88 52 70 90 75 83 66 64 53 94 92 71 78 98 97 65 86 81 64 97]


In [15]:
# 17. Stack two NumPy arrays vertically.

import numpy as np 

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.vstack((arr1,arr2)))

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
# 18. Stack two NumPy arrays horizontally.
import numpy as np 

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.hstack((arr1,arr2)))

[1 2 3 4 5 6 7 8]


In [22]:
# 19. Find the unique elements in an array.
import numpy as np 

arr1 = np.array([1,1,3,1])
arr2 = np.array([2,2,3,1])
print(np.unique((arr1,arr2)))

[1 2 3]


In [28]:
# 20. Replace all odd numbers in an array with -1.
import numpy as np
arr = np.array([1, 2, 3, 4, 5])

arr[arr % 2 != 0] = -1
print(arr)

[-1  2 -1  4 -1]


In [2]:
# 21. Convert a list to a NumPy array.
import numpy as np 
list = [1,2,3,4,5]

array = np.array(list)
print(array)

[1 2 3 4 5]


In [3]:
# 22. Convert a NumPy array to a Python list.

import numpy as np

array = np.array([1,2,3,4,5])
list = np.array(array)
print(list)

[1 2 3 4 5]


In [12]:
# 23. Find the shape and size of an array.

import numpy as np


[[1 2]
 [3 4]]


In [16]:
# 24. Flatten a multi-dimensional array.

# import numpy as np

# nested_array = np.array([[1, 2, 3], [4, 5], [6]])
# flattened = nested_array.flatten()
# print(flattened)


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [33]:
# 25. Find the index of the maximum value in an array.

import numpy as np
arr = np.array([10, 20, 5, 30, 25])
index = np.argmax(arr)
print(index)


3


In [37]:
# 26. Find the index of the minimum value in an array.

import numpy as np

arr = np.array([10,2,40,40])
min = np.argmin(arr)
print(min)

1


In [39]:
# 27. Sort a NumPy array in ascending order.

import numpy as np

arr = np.array([2,1,5,4,3])
arr1 = np.sort(arr)
print(arr1)

[1 2 3 4 5]


In [41]:
# 28. Sort a NumPy array in descending order.

import numpy as np
arr = np.array([1,2,3,4,5])

arr1 = arr[::-1]
print(arr1)

[5 4 3 2 1]


In [67]:
# 29. Generate a 5x5 array of random integers and find its transpose.

import numpy as np

arr = np.arange(0,25).reshape(5,5)

arr1= np.transpose(arr)
print("normal\n",arr)
print("Transpose\n",arr1)

normal
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Transpose
 [[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


In [69]:
# 30. Create an array and replace all values greater than 10 with 10.

import numpy as np

arr = np.array([5,16,9,23,1,11])

# for i in arr:
#     if i > 10:
#         arr[arr == i] = 10
#     else:
#         pass

arr[arr > 10] = 10
print(arr)

[ 5 10  9 10  1 10]


In [71]:
import numpy as np

arr = np.array([5,16,9,23,1,11])

# for i in arr:
#     if i > 10:
#         arr[arr == i] = 10
#     else:
#         pass

arr[arr > 10] = F
print(arr)

NameError: name 'F' is not defined