In [2]:
# 1. Import NumPy and check its version.

import numpy

numpy.__version__

'1.26.4'

In [2]:
# 2. Create a 1D NumPy array of numbers from 1 to 10.

print(numpy.arange(1, 11))

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# 3. Create a 2D NumPy array of shape (3,3) filled with zeros.

print(numpy.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# 4. Create a 3x3 identity matrix.

print(numpy.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# 5. Generate a NumPy array of 10 random numbers between 0 and 1.

import numpy as np

np.random.rand(10)

array([0.63577798, 0.36023082, 0.43114718, 0.47423763, 0.77212997,
       0.60006897, 0.19487162, 0.93788085, 0.30066132, 0.89218943])

In [30]:
# 6. Create an array of even numbers from 2 to 20.

np.arange(2, 21, 2)


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [31]:
# 7. Reverse a NumPy array.

arr = np.array([1,2,3,4,5])
arr[::-1]

array([5, 4, 3, 2, 1])

In [33]:
# 8. Find the maximum and minimum values in an array.

arr = np.array([1,2,3,4,5])

print(arr.max())
print(arr.min())

5
1


In [10]:
# 9. Find the mean, median, and standard deviation of an array.
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,0])

print(np.std(arr))
print(np.median(arr))
print(np.mean(arr))

2.8722813232690143
4.5
4.5


In [27]:
# 10. Reshape a 1D array into a 2D array.

import numpy as np

arr = np.array([1,2,3,4,5])
# np.reshape(arr, (1, 5))
print(arr)



[1 2 3 4 5]


In [34]:
# 11. Create a 4x4 matrix with values ranging from 0 to 15.

import numpy as np

arr = np.arange(0, 16).reshape(4, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [45]:
# 12. Extract the diagonal elements of a matrix.

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,0,11,12,13,14,15,16]).reshape(4, 4)
print(np.diag(arr))


[ 1  6 11 16]


In [47]:
# 13. Find the sum of all elements in an array.
import numpy as np 
 
arr = np.array([1,2,3,4,5,6,7,8])

arr = arr.sum()
print(arr)

36


In [2]:
# 14. Find the cumulative sum of elements in an array.

import numpy as np
arr = np.array([1, 2, 3, 4, 5])

cumulative_sum = np.cumsum(arr)
print(cumulative_sum)


[ 1  3  6 10 15]


In [5]:
# 15. Create a NumPy array with linearly spaced values between 0 and 1.

import numpy as np
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [14]:
# 16. Create an array of 20 random integers between 50 and 100.
import numpy as np

arr = np.random.randint(50, 100, 20)
print(arr)

[88 52 70 90 75 83 66 64 53 94 92 71 78 98 97 65 86 81 64 97]


In [15]:
# 17. Stack two NumPy arrays vertically.

import numpy as np 

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.vstack((arr1,arr2)))

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
# 18. Stack two NumPy arrays horizontally.
import numpy as np 

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.hstack((arr1,arr2)))

[1 2 3 4 5 6 7 8]


In [22]:
# 19. Find the unique elements in an array.
import numpy as np 

arr1 = np.array([1,1,3,1])
arr2 = np.array([2,2,3,1])
print(np.unique((arr1,arr2)))

[1 2 3]
